### ISSUE TITLE
sea3d exporter

### ISSUE THREAD

**Issue by DVLP** [sunag/sea3d_studio_sdk#2]
Issue tracking is disabled for Sea3d project but there's a bug in 3dsmax exporter which I want to report.

After clicking on "export" there's dropdown to choose either ".sea" or ".tjs.sea" file format. I was happy to see that it's finally possible to export directly to three.js without additional step of going through Sea3d Studio but unfortunately Sea3d loader in Three.js is throwing exception when trying to load this "file.tjs.sea" 

Sign 'SEA' not supported! Use SEA3D Studio to publish or SEA3DLegacy.js

**Comment by sunag** [comment]
Thanks @DVLP!

We disabled the `Issue` option in github because our support is in http://community.poonya.com

> After clicking on "export" there's dropdown to choose either ".sea" or ".tjs.sea" file format. I was happy to see that it's finally possible to export directly to three.js without additional step of going through Sea3d Studio but unfortunately Sea3d loader in Three.js is throwing exception when trying to load this "file.tjs.sea"

Please use the `sea3d.js` or `sea3d.min.js` both contains the `SEA3DLegacy.js`
https://github.com/sunag/sea3d/tree/master/Build/Three.JS

`TJS` is completely compatible with `SEA3D Studio`... `SEA3D Exporter` for a while export done only in `S3D`(default) struct.
For `TJS` support: Open in `SEA3D Studio` and `Publish` to `TJS`. Support `Open3DGC` too.
http://community.poonya.com/252 - SEA3D Studio 1.8
http://community.poonya.com/224 - Open3DGC
